config/routes.rb
Rails.application.routes.draw do

  resources :answers
  resources :questions

  root 'home#index'

  get '/about' => 'home#about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord

    include HasGravatar

    belongs_to :question

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord

    include HasGravatar

    has_many :answers

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

    def create
        question = Question.find(params[:answer][:question_id])

        question.answers.create(answer_params)

        redirect_to question
    end

    private

    def answer_params
        params.require(:answer).permit(:email, :body)    
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/concerns/has_gravatar.rb
module HasGravatar
    
    def gravatar
        "https://gravatar.com/avatar/#{Digest::MD5.hexdigest(email)}"
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @questions = Question.order(created_at: :desc).all
  end

  def about
  end

  def temp
    redirect_to root_path
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

    def show
        @question = Question.find(params[:id])

        @answers = @question.answers.order(created_at: :desc)
    end

    def create
        Question.create(question_params)

        redirect_to root_path
    end

    private

    def question_params
        params.require(:question).permit(:email, :body)
    end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/home/_navbar.html.erb
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">History of the Universe</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
            <li>
            <form>
                <a href="#" class="btn btn-success navbar-btn btn-sm" data-toggle="modal" data-target="#new-question-modal">
                Ask Question
                </a>
            </form>
            </li>
        </ul>
        </div>
    </div>
</nav>

app/views/home/_new_answer_form.html.erb
<div class="modal fade" tabindex="-1" role="dialog" id="new-answer-modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">New Answer</h4>
            </div>
            <%= form_for :answer, url: '/answers', html: { class: 'form-horizontal' } do %>
                <input type="hidden" name="answer[question_id]" value="<%= @question.id %>">
                <div class="modal-body">
                    <div class="form-group">
                        <label for="inputEmail" class="col-sm-2 control-label">Email</label>
                        <div class="col-sm-10">
                            <input type="email" name="answer[email]" class="form-control" id="inputEmail" placeholder="Email" required>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputAnswer" class="col-sm-2 control-label">Answer</label>
                        <div class="col-sm-10">
                            <textarea id="inputAnswer" name="answer[body]" class="form-control" placeholder="What is your answer?" required></textarea>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            <% end %>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/home/_new_question_form.html.erb
<div class="modal fade" tabindex="-1" role="dialog" id="new-question-modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">New Question</h4>
            </div>
            <%= form_for :question, url: '/questions', html: { class: 'form-horizontal' } do %>
                <div class="modal-body">
                    <div class="form-group">
                        <label for="inputEmail" class="col-sm-2 control-label">Email</label>
                        <div class="col-sm-10">
                            <input type="email" name="question[email]" class="form-control" id="inputEmail" placeholder="Email" required>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputQuestion" class="col-sm-2 control-label">Question</label>
                        <div class="col-sm-10">
                            <textarea id="inputQuestion" name="question[body]" class="form-control" placeholder="What would you like to know?" required></textarea>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            <% end %>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/home/about.html.erb
<h1>About us</h1>

app/views/home/index.html.erb
<div class="well">
    <h4>The Universe is the totality of everything that exists, has existed, or ever will exist.</h4>
    <p>The Q&A site is dedicated to questions about the history of the Universe</p>
</div>

<div class="container">

    <% @questions.each do |q|%>
        <div class="media">
            <div class="media-left">
                <a href="#">
                    <img class="media-object" src="<%= q.gravatar %>" alt="<%= q.email %>">
                </a>
            </div>
            <div class="media-body">
                <h4 class="media-heading"><%= q.email %> asked:</h4>

                <div><%= time_ago_in_words q.created_at %> ago</div>
                <%= q.body %>

                <div>
                    <a href="<%= question_path(q)%>" class="btn btn-success btn-xs">View Answers</a>
                </div>
            </div>
        </div>
    <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HU</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <script src="http://code.jquery.com/jquery-2.2.4.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'home/navbar' %>

    <%= yield %>

    <%= render 'home/new_question_form' %>

  </body>

</html>

app/views/questions/show.html.erb
<div class="container">
    <div class="lead well">
        <div class="media">
            <div class="media-left">
                <a href="#">
                    <img class="media-object" src="<%= @question.gravatar %>" alt="...">
                </a>
            </div>
            <div class="media-body">
                <h4 class="media-heading"><%= @question.email %> asked:</h4>
                
                <%= @question.body %>

            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-8 col-sm-offset-2">

            <div>
                <button class="btn btn-success btn-sm" type="button" data-toggle="modal" data-target="#new-answer-modal">Submit new answer</button>
            </div>

            <%= render 'home/new_answer_form' %>

            <% @answers.each do |answer| %>
                <div class="media">
                    <div class="media-left">
                        <a href="#">
                            <img class="media-object" src="<%= answer.gravatar %>" alt="<%= answer.email %>">
                        </a>
                    </div>
                    <div class="media-body">
                        <h4 class="media-heading"><%= answer.email %> answered:</h4>
                        
                        <div><%= time_ago_in_words answer.created_at %> ago</div>
                        <%= answer.body %>

                    </div>
                </div>
            <% end %>
            
        </div>
    </div>
</div>